### ISSUE TITLE
Discuss for sigma and timesteps implementations

### ISSUE THREAD

**Issue by jiangzhengkai** [G-U-N/AnimateLCM#25]
@G-U-N Hi，thanks for your great work.

I have finetune svd using the following way generating sigma and timesteps, which is consistent with EDMv2 paper

My implementation:
<img width="535" alt="企业微信截图_17157433189090" src="https://github.com/G-U-N/AnimateLCM/assets/19780166/2a1b7498-8504-421a-b918-98c0d09b9023">

EMDv2:
<img width="297" alt="企业微信截图_1715743379560" src="https://github.com/G-U-N/AnimateLCM/assets/19780166/71f70aa3-ea4a-4701-90ac-1998a09e7666">

You seems follow the original EDM paper implementation. Have you compare with EDMv2 way？

**Comment by G-U-N** [comment]
Hi @jiangzhengkai, very glad for your interest.  I am not sure about the difference of your mentioned EDM and EDMv2. But looks like your implementation is exactly how the SVD was tuned? I also used that format. Could you elaborate more on that?

**Comment by jiangzhengkai** [comment]
@G-U-N Yes, I follow a public repo [SVD_Xtend](https://github.com/pixeli99/SVD_Xtend/blob/layout-control/train_svd.py). After read the EDM paper, I think your implementation is more close to origin paper. Have you compare the two implementation choices? Which one is better?

<img width="1105" alt="图片" src="https://github.com/G-U-N/AnimateLCM/assets/19780166/4e45c99d-805f-4834-9eb1-ddc040f1bedd">

**Comment by G-U-N** [comment]
Hey @jiangzhengkai ,

I see. It's about the timestep/sigma sampling in training.

I hope to clarify that the original EDM is exactly trained as your implementation instead of mine. The red square is about sigma sampling for  generation.  For training,  the sigma/timestep sampling is listed in the third row of the table, which is the same as your implementation.

Go back to my implementation,  the reason I use the discretization  sigma/timestep sampling instead of  the continuous sampling as the original implementation is to facilitate the consistency training process. Only in this way, the teacher diffusion model will always induce the same empirical ODE trajectory due to the fixed discretized sigma sampling. 

 Hope this clarifies any confusion.

**Comment by jiangzhengkai** [comment]
@G-U-N Thanks for your explain.
