### ISSUE TITLE
How to install triton for python 3.9

### ISSUE THREAD

**Issue by nikhil8399** [G-U-N/AnimateLCM#29]
File "C:\Users\SHREE\anaconda3\envs\animatelcm_svd\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\SHREE\anaconda3\envs\animatelcm_svd\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'

please tell me how to install triton on python 3.9

**Comment by G-U-N** [comment]
Why not ask GPT?
> 
To install the "triton" package for Python 3.9, you can use pip, Python's package installer. Since "triton" is not a standard Python package, you need to make sure it's available for your Python version and platform. Here are the steps:

1. **Check Compatibility**: Ensure that "triton" is compatible with Python 3.9. You can usually find this information on the package's documentation or its PyPI page.

2. **Install via pip**: Open your command line or terminal and run the following command:

   ```
   pip install triton
   ```

   This command will attempt to download and install the "triton" package and its dependencies. If successful, you should be able to import it into your Python environment.

3. **Verify Installation**: After installation, you can verify that "triton" is installed correctly by launching Python in your terminal and attempting to import it:

   ```
   python
   >>> import triton
   ```

   If there are no errors, the installation was successful, and you can use "triton" in your projects.

4. **Additional Notes**: Sometimes, packages may have additional requirements or dependencies. Make sure you fulfill those requirements if specified.

Following these steps should help you install the "triton" package for Python 3.9. Let me know if you encounter any issues along the way!
