### ISSUE TITLE
is this project similar to videolcm?

### ISSUE THREAD

**Issue by TruthSearcher** [G-U-N/AnimateLCM#3]
https://arxiv.org/abs/2312.09109

**Comment by G-U-N** [comment]
Hi, thanks for sharing this great work. I just read the technical report from the Ali-Vilab, and it looks like they have done many explorations in video generation and acceleration. While I am not very sure about what you mentioned as 'similar,' since many details are not explicitly written and they do not open-source the model. We might cite this paper (since they seem to be earlier) when revising our paper.
